// Every editable string on the marketing site, keyed by a stable id.
// Generated from the AMFIRE standalone design; the admin Content Manager
// ("Page text" section) writes overrides for any of these keys.
export const textDefaults: Record<string, string> = {
  "about.about-us": "About Us",
  "about.one-team-full": "One team. Full",
  "about.accountability": "accountability",
  "about.we-re-an-ai-engineering-team": "We're an AI engineering team building intelligent digital products end-to-end — in production, for Indian businesses. No founder bios, no team photos. The platforms we've shipped speak for us.",
  "about.see-our-work": "See our work",
  "about.start-a-conversation": "Start a conversation",
  "about.what-we-stand-for": "what we stand for",
  "about.real-ai-in-production": "Real AI in production",
  "about.full-stack-ownership": "Full-stack ownership",
  "about.100-ip-to-you": "100% IP to you",
  "about.why-amfire": "Why amfire",
  "about.six-commitments-that-shape-every-engagement": "Six commitments that shape every engagement",
  "about.01": "01",
  "about.real-ai-not-a-dashboard": "Real AI, not a dashboard",
  "about.adaptive-engines-and-autonomous-agents-running": "Adaptive engines and autonomous agents running in production — not a static graph relabelled \"AI Insights\".",
  "about.02": "02",
  "about.full-stack-ownership-2": "Full-stack ownership",
  "about.frontend-backend-ai-deployment-one-team": "Frontend, backend, AI, deployment. One team, one point of contact — no vendor-blaming, no handoff gaps.",
  "about.03": "03",
  "about.india-first-engineering": "India-first engineering",
  "about.built-for-indian-workflows-hierarchies-and": "Built for Indian workflows, hierarchies, and infrastructure — not a Western SaaS forced into local context.",
  "about.04": "04",
  "about.transparent-scope": "Transparent scope",
  "about.what-s-in-the-proposal-is": "What's in the proposal is what gets built. Changes are quoted before they're billed. No hidden charges.",
  "about.05": "05",
  "about.agentic-architecture": "Agentic architecture",
  "about.multi-agent-systems-that-coordinate-autonomously": "Multi-agent systems that coordinate autonomously, 24/7 — the way modern software should run.",
  "about.06": "06",
  "about.post-launch-partnership": "Post-launch partnership",
  "about.dedicated-support-after-delivery-we-stay": "Dedicated support after delivery. We stay behind the work until it succeeds.",
  "about.how-we-engage": "How we engage",
  "about.simple-written-and-fair-the-same": "Simple, written, and fair — the same way on every project.",
  "about.payment": "Payment",
  "about.milestone-based-20-at-kickoff-scaling": "Milestone-based — 20% at kickoff, scaling to full payment at launch. You pay as value ships, never upfront in full.",
  "about.scope": "Scope",
  "about.agreed-in-writing-before-we-start": "Agreed in writing before we start. Any change is quoted before it's billed — never after.",
  "about.ownership": "Ownership",
  "about.100-of-the-ip-transfers-to": "100% of the IP transfers to you on final payment. The code is yours.",
  "about.we-stay-behind-the-work-not": "We stay behind the work, not in front of it.\"",
  "about.start-a-conversation-2": "Start a conversation",
  "casestudy.work": "Work",
  "casestudy.skillship": " /  Skillship",
  "casestudy.drop-the-product-screenshot": "Drop the product screenshot",
  "casestudy.case-study": "Case Study",
  "casestudy.skillship-2": "Skillship",
  "casestudy.a-complete-ai-education-ecosystem-live": "A complete AI education ecosystem, live in 20+ schools within one academic year.",
  "casestudy.edtech": "EdTech",
  "casestudy.next-js-react-ai-ml": "Next.js · React · AI/ML",
  "casestudy.skillship-in": "skillship.in ↗",
  "casestudy.01": "01",
  "casestudy.ai-career-pilot-in-action": "AI Career Pilot in action",
  "casestudy.ai-career-pilot": "AI Career Pilot",
  "casestudy.personalised-from-day-one": "Personalised, from day one",
  "casestudy.every-student-gets-a-career-roadmap": "Every student gets a career roadmap built around their own goals — forward and backward planned from current class to dream career.",
  "casestudy.02": "02",
  "casestudy.students-in-a-hands-on-lab": "Students in a hands-on lab",
  "casestudy.8-advanced-labs": "8 advanced labs",
  "casestudy.hands-on-not-theoretical": "Hands-on, not theoretical",
  "casestudy.robotics-ai-and-iot-modules-with": "Robotics, AI, and IoT modules with real hardware kits and a guided curriculum teachers can run without a technical background.",
  "casestudy.03": "03",
  "casestudy.college-finder-screenshot": "College finder screenshot",
  "casestudy.college-finder": "College finder",
  "casestudy.deadlines-that-find-you": "Deadlines that find you",
  "casestudy.a-nirf-ranked-database-with-automated": "A NIRF-ranked database with automated admission-deadline alerts, tailored to each student's shortlist.",
  "casestudy.20": "20+",
  "casestudy.schools-live": "Schools live",
  "casestudy.1-400": "1,400+",
  "casestudy.career-paths-generated": "Career paths generated",
  "casestudy.12": "12+",
  "casestudy.skill-domains-covered": "Skill domains covered",
  "casestudy.94": "94%",
  "casestudy.teacher-certification-rate": "Teacher certification rate",
  "casestudy.skillship-gave-our-teachers-a-certification": "Skillship gave our teachers a certification path and our students a career roadmap — in the same platform. It replaced four vendors we were juggling before.",
  "casestudy.rk": "RK",
  "casestudy.ritu-kapoor": "Ritu Kapoor",
  "casestudy.principal-skillship-partner-school": "Principal, Skillship Partner School",
  "casestudy.more-work": "More work",
  "casestudy.other-projects-we-ve-shipped": "Other projects we've shipped",
  "casestudy.iot-mobile": "IoT · Mobile",
  "casestudy.mygreenhome": "MyGreenHome",
  "casestudy.smart-home-automation": "Smart-home automation",
  "casestudy.live-product": "Live Product",
  "casestudy.ai-career-copilot": "AI Career Copilot",
  "casestudy.bilingual-career-ai": "Bilingual career AI",
  "casestudy.see-all-projects": "See all projects →",
  "casestudy.need-something-similar": "Need something similar?",
  "casestudy.start-your-project": "Start your project",
  "casestudy.visit-skillship-in": "Visit skillship.in ↗",
  "contact.contact": "Contact",
  "contact.let-s-build": "Let's build",
  "contact.together": "together",
  "contact.tell-us-about-your-project-we": "Tell us about your project. We'll respond within 48 hours with a detailed proposal — scope, timeline, and milestone plan.",
  "contact.prefer-whatsapp": "Prefer WhatsApp?",
  "contact.message-us-and-we-ll-reply": "Message us and we'll reply fast.",
  "contact.chat": "Chat →",
  "contact.contact-amfire-in": "✉ contact@amfire.in",
  "contact.amfire-in": "↗ amfire.in",
  "contact.what-happens-next": "What happens next",
  "contact.we-review-your-message-within-24": "We review your message within 24 hours",
  "contact.a-detailed-proposal-lands-in-your": "A detailed proposal lands in your inbox within 48 hours",
  "contact.kickoff-scheduled-async-or-over-chat": "Kickoff scheduled — async or over chat, at your convenience",
  "contact.step-2-of-4": "Step 2 of 4",
  "contact.what-are-you-looking-to-build": "What are you looking to build?",
  "contact.pick-the-closest-we-ll-tailor": "Pick the closest — we'll tailor the proposal.",
  "contact.web-app": "Web App",
  "contact.mobile-app": "Mobile App",
  "contact.ai-agent": "AI Agent",
  "contact.automation": "Automation",
  "contact.full-product": "Full Product",
  "contact.something-else": "Something else",
  "contact.approximate-budget": "Approximate budget",
  "contact.20k": "₹20K",
  "contact.50k": "₹50K",
  "contact.75k": "₹75K+",
  "contact.back": "← Back",
  "contact.next": "Next →",
  "footer.am": "am",
  "footer.fire": "fire",
  "footer.ai-first-digital-solutions-complete-software": "AI-First Digital Solutions. Complete software, real intelligence — built end-to-end in India.",
  "footer.stay-in-the-loop": "Stay in the loop",
  "footer.insights-on-ai-builds-and-what": "Insights on AI, builds, and what we're shipping.",
  "footer.your-email-com": "your@email.com",
  "footer.services": "Services",
  "footer.web-development": "Web Development",
  "footer.mobile-apps": "Mobile Apps",
  "footer.ai-agents": "AI Agents",
  "footer.automation": "Automation",
  "footer.cloud-devops": "Cloud & DevOps",
  "footer.company": "Company",
  "footer.about": "About",
  "footer.work": "Work",
  "footer.products": "Products",
  "footer.pricing": "Pricing",
  "footer.contact": "Contact",
  "footer.get-in-touch": "Get in touch",
  "footer.contact-amfire-in": "✉ contact@amfire.in",
  "footer.amfire-in": "↗ amfire.in",
  "footer.2026-amfire-all-rights-reserved": "© 2026 amfire. All rights reserved.",
  "footer.privacy-policy-terms-of-service": "Privacy Policy · Terms of Service",
  "home.now-open-for-new-projects": "Now open for new projects",
  "home.we-build": "We build",
  "home.automation": "automation",
  "home.that-never-sleeps": "that never sleeps",
  "home.built-for-speed": "Built for speed",
  "home.ship-faster-with-ai-at-every": "Ship faster with AI at every step",
  "home.built-for-clarity": "Built for clarity",
  "home.full-transparency-zero-surprises": "Full transparency, zero surprises",
  "home.built-for-impact": "Built for impact",
  "home.smart-solutions-that-drive-real-results": "Smart solutions that drive real results",
  "home.get-a-custom-proposal": "Get a Custom Proposal →",
  "home.explore-client-portal": "Explore Client Portal",
  "home.ai-powered": "AI-Powered",
  "home.intelligent-automation-built-to-adapt": "Intelligent automation built to adapt",
  "home.end-to-end": "End-to-End",
  "home.from-idea-to-deployment-we-handle": "From idea to deployment, we handle it all",
  "home.always-on": "Always On",
  "home.real-time-updates-anytime-anywhere": "Real-time updates, anytime, anywhere",
  "home.secure-reliable": "Secure & Reliable",
  "home.enterprise-grade-security-you-can-trust": "Enterprise-grade security you can trust",
  "home.project-skillship-lms": "Project: Skillship LMS",
  "home.on-track": "On Track",
  "home.milestone-3-of-4-ai-integration": "Milestone 3 of 4 · AI Integration",
  "home.72": "72%",
  "home.discovery": "Discovery",
  "home.done": "Done",
  "home.design": "Design",
  "home.done-2": "Done",
  "home.development": "Development",
  "home.in-progress": "In Progress",
  "home.testing": "Testing",
  "home.upcoming": "Upcoming",
  "home.launch": "Launch",
  "home.upcoming-2": "Upcoming",
  "home.staging-v3-pdf": "Staging_v3.pdf",
  "home.2-4-mb-design": "2.4 MB · Design",
  "home.qa-sign-off": "QA sign-off",
  "home.approved-mar-30": "Approved · Mar 30",
  "home.milestone-shipped": "Milestone shipped",
  "home.2-hours-ago": "2 hours ago",
  "home.what-we-build": "What We Build",
  "home.full-stack-ai-native-end-to": "Full-stack, AI-native, end to end",
  "home.one-team-owns-the-whole-surface": "One team owns the whole surface — frontend, backend, AI, and deployment. No handoff gaps, no vendor-blaming.",
  "home.amfire": "AMFIRE",
  "home.product": "Product",
  "home.solutions": "Solutions",
  "home.resources": "Resources",
  "home.get-started": "Get Started",
  "home.build-faster-launch-smarter-scale-without": "Build faster. Launch smarter. Scale without limits.",
  "home.we-build-digital-products-that-drive": "We build digital products that drive real impact.",
  "home.get-started-2": "Get Started",
  "home.view-demo": "View Demo",
  "home.amfire-2": "AMFIRE",
  "home.build-faster-launch-smarter": "Build faster. Launch smarter.",
  "home.get-started-3": "Get Started",
  "home.01": "01",
  "home.web-development": "Web Development",
  "home.most-requested": "Most requested",
  "home.custom-platforms-client-portals-and-saas": "Custom platforms, client portals, and SaaS builds — pixel-perfect, fast-loading, SEO-ready.",
  "home.02": "02",
  "home.mobile-apps": "Mobile Apps",
  "home.react-native-ios-android-with-offline": "React Native iOS + Android with offline support, push notifications, and app-store delivery.",
  "home.ios": "iOS",
  "home.android": "Android",
  "home.dashboard": "Dashboard",
  "home.clicks": "Clicks",
  "home.12-4k": "12.4K",
  "home.12-5": "+12.5%",
  "home.revenue": "Revenue",
  "home.32-8k": "$32.8K",
  "home.12-9": "+12.9%",
  "home.messages": "Messages",
  "home.olivia-riye": "Olivia Riye",
  "home.liam-carter": "Liam Carter",
  "home.ethan-brooks": "Ethan Brooks",
  "home.ava-morgan": "Ava Morgan",
  "home.03": "03",
  "home.ai-agents": "AI Agents",
  "home.autonomous-agents-that-perform-tasks-coordinate": "Autonomous agents that perform tasks, coordinate, and make decisions 24/7.",
  "home.user-request": "User Request",
  "home.documents": "Documents",
  "home.database": "Database",
  "home.apis": "APIs",
  "home.agent-running": "Agent running",
  "home.reasoning": "Reasoning",
  "home.action": "Action",
  "home.response": "Response",
  "home.04": "04",
  "home.automation-2": "Automation",
  "home.kill-manual-workflows-data-pipelines-whatsapp": "Kill manual workflows — data pipelines, WhatsApp, and no-code integrations.",
  "home.trigger": "Trigger",
  "home.new-form-submission": "New Form Submission",
  "home.process": "Process",
  "home.validate-transform": "Validate & Transform",
  "home.action-2": "Action",
  "home.send-email-whatsapp": "Send Email / WhatsApp",
  "home.result": "Result",
  "home.update-crm-notify": "Update CRM & Notify",
  "home.workflows-run": "Workflows Run",
  "home.12-842": "12,842",
  "home.success-rate": "Success Rate",
  "home.99-7": "99.7%",
  "home.05": "05",
  "home.cloud-devops": "Cloud & DevOps",
  "home.ci-cd-pipelines-and-containerised-deploys": "CI/CD pipelines and containerised deploys on AWS/GCP/Hetzner with full SSL and DNS.",
  "home.code": "Code",
  "home.build": "Build",
  "home.test": "Test",
  "home.deploy": "Deploy",
  "home.aws": "aws",
  "home.production": "Production",
  "home.healthy": "Healthy",
  "home.uptime": "Uptime",
  "home.99-99": "99.99%",
  "home.deployments": "Deployments",
  "home.42": "42",
  "home.this-month": "this month",
  "home.06": "06",
  "home.ui-ux-design": "UI/UX Design",
  "home.figma-based-user-tested-design-systems": "Figma-based, user-tested design systems — we design the product before a line of code.",
  "home.share": "Share",
  "home.100": "100%",
  "home.layers": "Layers",
  "home.header": "Header",
  "home.hero": "Hero",
  "home.features": "Features",
  "home.pricing": "Pricing",
  "home.footer": "Footer",
  "home.headline": "Headline",
  "home.medium-title-goes-here": "Medium title goes here",
  "home.primary-button": "Primary Button",
  "home.design-2": "Design",
  "home.frame": "Frame",
  "home.24": "24",
  "home.96": "96",
  "home.1200": "1200",
  "home.680": "680",
  "home.colors": "Colors",
  "home.unique-to-amfire": "Unique to amfire",
  "home.real-time-project-visibility": "Real-time project visibility",
  "home.most-agencies-go-dark-after-kickoff": "Most agencies go dark after kickoff. We give every client a live portal: milestone progress, staging links, documents, and payments — all in one place, updated as we ship.",
  "home.milestone-tracker-with-staging-previews": "Milestone tracker with staging previews",
  "home.documents-invoices-payments-in-one-view": "Documents, invoices & payments in one view",
  "home.feedback-threads-tied-to-each-deliverable": "Feedback threads tied to each deliverable",
  "home.try-the-demo-portal": "Try the Demo Portal →",
  "home.milestones": "Milestones",
  "home.live": "Live",
  "home.design-backend-on-staging": "Design + Backend on staging",
  "home.done-3": "Done",
  "home.ai-integration": "AI Integration",
  "home.72-2": "72%",
  "home.production-launch": "Production Launch",
  "home.sprint-notes-pdf": "Sprint_notes.pdf",
  "home.updated-today": "Updated today",
  "home.invoice-0032": "Invoice #0032",
  "home.paid-1-25l": "Paid · ₹1.25L",
  "home.our-process": "Our Process",
  "home.7-steps-always-on-time": "7 steps, always on time",
  "home.from-idea-to-impact-a-proven": "From idea to impact — a proven pipeline that keeps every stage visible, never just the end.",
  "home.img-search": "/amfire-design/process/search-sharp.png",
  "home.01-2": "01",
  "home.discovery-2": "Discovery",
  "home.understand-your-goals-and-uncover-opportunities": "Understand your goals and uncover opportunities.",
  "home.3-5-days": "3–5 days",
  "home.img-connector": "/amfire-design/process/connector-sharp.png",
  "home.img-cubes": "/amfire-design/process/cubes-sharp.png",
  "home.02-2": "02",
  "home.architecture": "Architecture",
  "home.design-a-robust-scalable-blueprint": "Design a robust, scalable blueprint.",
  "home.2-3-days": "2–3 days",
  "home.img-connector-2": "/amfire-design/process/connector-sharp.png",
  "home.img-browser": "/amfire-design/process/browser-sharp.png",
  "home.03-2": "03",
  "home.ui-ux": "UI/UX",
  "home.craft-intuitive-experiences-users-love": "Craft intuitive experiences users love.",
  "home.4-6-days": "4–6 days",
  "home.img-connector-3": "/amfire-design/process/connector-sharp.png",
  "home.img-frontend": "/amfire-design/process/frontend-sharp.png",
  "home.04-2": "04",
  "home.frontend": "Frontend",
  "home.build-fast-responsive-modern-interfaces": "Build fast, responsive, modern interfaces.",
  "home.5-7-days": "5–7 days",
  "home.img-connector-4": "/amfire-design/process/connector-sharp.png",
  "home.img-servers": "/amfire-design/process/servers-sharp.png",
  "home.05-2": "05",
  "home.backend": "Backend",
  "home.power-the-product-with-secure-apis": "Power the product with secure APIs.",
  "home.4-6-days-2": "4–6 days",
  "home.img-connector-5": "/amfire-design/process/connector-sharp.png",
  "home.img-brain": "/amfire-design/process/brain-sharp.png",
  "home.06-2": "06",
  "home.ai-integration-2": "AI Integration",
  "home.integrate-intelligent-capabilities": "Integrate intelligent capabilities.",
  "home.3-5-days-2": "3–5 days",
  "home.img-connector-6": "/amfire-design/process/connector-sharp.png",
  "home.img-rocket": "/amfire-design/process/rocket-sharp.png",
  "home.07": "07",
  "home.deploy-2": "Deploy",
  "home.launch-smoothly-with-continuous-delivery": "Launch smoothly with continuous delivery.",
  "home.1-2-days": "1–2 days",
  "home.real-work": "Real Work",
  "home.real-work-2": "Real work.",
  "home.real-impact": "Real impact.",
  "home.no-stock-logos-no-invented-case": "No stock logos, no invented case studies —",
  "home.the-platforms-we-ve-actually-shipped": "the platforms we've actually shipped.",
  "home.view-all-work": "View all work",
  "home.20": "20+",
  "home.projects-delivered": "Projects Delivered",
  "home.10k": "10K+",
  "home.users-impacted": "Users Impacted",
  "home.3": "3+",
  "home.industries-served": "Industries Served",
  "home.edtech": "EdTech",
  "home.skillship": "Skillship",
  "home.ai-powered-learning-and-placement-guidance": "AI-powered learning and placement guidance platform.",
  "home.20-2": "20+",
  "home.schools-automated": "Schools Automated",
  "home.10k-2": "10K+",
  "home.students-impacted": "Students Impacted",
  "home.skillship-dashboard-screenshot": "Skillship dashboard screenshot",
  "home.iot-mobile": "IoT · Mobile",
  "home.mygreenhome": "MyGreenHome",
  "home.smart-home-automation-for-energy-efficiency": "Smart-home automation for energy efficiency and sustainable living.",
  "home.mygreenhome-2": "MyGreenHome",
  "home.overview": "Overview",
  "home.devices": "Devices",
  "home.scenes": "Scenes",
  "home.energy-usage": "Energy Usage",
  "home.today": "Today",
  "home.2-45": "2.45",
  "home.kwh": "kWh",
  "home.12-vs-yesterday": "-12% vs yesterday",
  "home.living-room": "Living Room",
  "home.24-c": "24°C",
  "home.cooling": "Cooling",
  "home.ai-web": "AI · Web",
  "home.ai-career-copilot": "AI Career Copilot",
  "home.bilingual-ai-career-guidance-platform-for": "Bilingual AI career guidance platform for students.",
  "home.career-matches": "Career Matches",
  "home.85": "85%",
  "home.great-match": "Great Match",
  "home.data-scientist": "Data Scientist",
  "home.ml-engineer": "ML Engineer",
  "home.ai-analyst": "AI Analyst",
  "home.recommended-next-steps": "Recommended Next Steps",
  "home.build-ml-project": "Build ML Project",
  "home.in-progress-2": "In Progress",
  "home.trusted-by": "Trusted by",
  "home.schools": "Schools",
  "home.enterprises": "Enterprises",
  "home.government": "Government",
  "home.ngos": "NGOs",
  "home.our-products": "OUR PRODUCTS",
  "home.tools-we-build": "Tools we build.",
  "home.problems-we": "Problems we",
  "home.solve": "solve.",
  "home.ai-powered-products-built-to-simplify": "AI-powered products built to simplify operations, enhance decisions, and drive real-world impact.",
  "home.explore-all-products": "Explore all products →",
  "home.5": "5+",
  "home.products": "Products",
  "home.10k-3": "10K+",
  "home.users": "Users",
  "home.3-2": "3+",
  "home.industries": "Industries",
  "home.graduation-cap-books-illustration": "Graduation cap + books illustration",
  "home.skillship-2": "SkillShip",
  "home.ai-powered-learning-and-placement-guidance-2": "AI-powered learning and placement guidance platform for students.",
  "home.learn-more": "Learn more →",
  "home.ai-robot-resume-illustration": "AI robot + resume illustration",
  "home.ai-career-copilot-2": "AI Career Copilot",
  "home.bilingual-career-guidance-ai-that-helps": "Bilingual career guidance AI that helps students discover paths, prepare, and succeed.",
  "home.learn-more-2": "Learn more →",
  "home.smart-home-solar-panels-illustration": "Smart-home + solar panels illustration",
  "home.mygreenhome-3": "MyGreenHome",
  "home.smart-solutions-for-energy-efficiency-sustainability": "Smart solutions for energy efficiency, sustainability, and greener living.",
  "home.learn-more-3": "Learn more →",
  "home.view-all-products": "View all products",
  "home.client-voices": "Client voices",
  "home.in-their-words": "In their words",
  "home.from-startups-to-enterprises-built-with": "From startups to enterprises — built with care, shipped with confidence.",
  "home.amfire-rebuilt-our-entire-backend-with": "amfire rebuilt our entire backend with a RAG system that reads contracts and flags risks automatically. It's become our most-loved internal tool.",
  "home.sr": "SR",
  "home.sneha-rao": "Sneha Rao",
  "home.cto-nexahealth": "CTO, NexaHealth",
  "home.they-delivered-our-construction-saas-in": "They delivered our construction SaaS in 10 weeks — full AI document processing, multi-tenant architecture, and a polished UI. Best dev engagement we've had.",
  "home.am": "AM",
  "home.arjun-mehta": "Arjun Mehta",
  "home.ceo-clearpath": "CEO, Clearpath",
  "home.they-understood-exactly-what-we-needed": "They understood exactly what we needed for our EdTech platform. The AI tutor they built dramatically improved student engagement.",
  "home.ps": "PS",
  "home.priya-sharma": "Priya Sharma",
  "home.founder-eduforge": "Founder, EduForge",
  "home.ready-to-automate-your-business": "Ready to automate your business?",
  "home.tell-us-what-you-re-building": "Tell us what you're building — we'll send a detailed proposal within 48 hours.",
  "home.get-a-proposal": "Get a Proposal",
  "home.whatsapp-us": "WhatsApp us",
  "nav.am": "am",
  "nav.fire": "fire",
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.products": "Products",
  "nav.work": "Work",
  "nav.pricing": "Pricing",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.get-a-proposal": "Get a Proposal →",
  "pricing.pricing": "Pricing",
  "pricing.plans-that-grow-as-fast-as": "Plans that grow as fast as",
  "pricing.you-do": "you do.",
  "pricing.flexible-ai-solutions-for-every-stage": "Flexible AI solutions for every stage of your journey.",
  "pricing.upgrade-scale-or-customize-all-without": "Upgrade, scale, or customize — all without limits.",
  "pricing.monthly": "Monthly",
  "pricing.yearly": "Yearly",
  "pricing.save-up-to-20": "Save up to 20%",
  "pricing.img-timeline-wave": "/amfire-design/pricing/timeline-wave.svg",
  "pricing.01": "01",
  "pricing.02": "02",
  "pricing.03": "03",
  "pricing.most-popular": "Most Popular",
  "pricing.04": "04",
  "pricing.starter": "Starter",
  "pricing.for-individuals-and-small-teams-getting": "For individuals and small teams getting started with AI.",
  "pricing.19-999": "₹19,999",
  "pricing.mo": "/mo",
  "pricing.5-ai-agents": "5 AI agents",
  "pricing.5-workflow-automations": "5 workflow automations",
  "pricing.whatsapp-website-chatbot": "WhatsApp / Website chatbot",
  "pricing.crm-setup-training-call": "CRM setup + training call",
  "pricing.30-day-free-support": "30-day free support",
  "pricing.start-your-project": "Start your project",
  "pricing.growth": "Growth",
  "pricing.for-growing-businesses-ready-to-automate": "For growing businesses ready to automate and scale.",
  "pricing.49-999": "₹49,999",
  "pricing.mo-2": "/mo",
  "pricing.10-ai-agents": "10 AI agents",
  "pricing.10-custom-automations": "10 custom automations",
  "pricing.ai-powered-saas-website": "AI-powered SaaS website",
  "pricing.performance-dashboard": "Performance dashboard",
  "pricing.60-day-free-support": "60-day free support",
  "pricing.start-your-project-2": "Start your project",
  "pricing.scale": "Scale",
  "pricing.for-established-teams-scaling-ai-across": "For established teams scaling AI across operations.",
  "pricing.74-999": "₹74,999",
  "pricing.mo-3": "/mo",
  "pricing.15-custom-automations": "15 custom automations",
  "pricing.ai-voice-receptionist": "AI voice receptionist",
  "pricing.advanced-analytics": "Advanced analytics",
  "pricing.ai-enhanced-crm": "AI-enhanced CRM",
  "pricing.60-day-premium-support": "60-day premium support",
  "pricing.start-your-project-3": "Start your project",
  "pricing.enterprise": "Enterprise",
  "pricing.for-large-organizations-needing-a-tailored": "For large organizations needing a tailored AI operating system.",
  "pricing.custom": "Custom",
  "pricing.multi-lingual-generative-saas": "Multi-lingual generative SaaS",
  "pricing.15-25-ai-agents": "15–25 AI agents",
  "pricing.20-automations": "20+ automations",
  "pricing.dedicated-ai-account-manager": "Dedicated AI account manager",
  "pricing.90-day-premium-support": "90-day premium support",
  "pricing.contact-our-team": "Contact our team",
  "pricing.no-long-term-contracts": "No long-term contracts",
  "pricing.cancel-anytime": "Cancel anytime,",
  "pricing.no-questions-asked": "no questions asked.",
  "pricing.onboard-in-48-hours": "Onboard in 48 hours",
  "pricing.quick-setup": "Quick setup,",
  "pricing.fast-results": "fast results.",
  "pricing.bank-level-security": "Bank-level security",
  "pricing.your-data-is-encrypted": "Your data is encrypted",
  "pricing.and-always-protected": "and always protected.",
  "pricing.human-support": "Human support",
  "pricing.talk-to-real-people": "Talk to real people",
  "pricing.who-actually-care": "who actually care.",
  "pricing.built-for-scale": "Built for scale",
  "pricing.upgrade-or-downgrade": "Upgrade or downgrade",
  "pricing.as-you-grow": "as you grow.",
  "pricing.how-you-pay": "How you pay",
  "pricing.milestone-based-payments": "Milestone-based payments",
  "pricing.you-pay-as-value-is-delivered": "You pay as value is delivered — never upfront, always tied to real progress.",
  "pricing.20": "20%",
  "pricing.img-kickoff": "/amfire-design/pricing/kickoff.png",
  "pricing.project-kickoff": "Project kickoff",
  "pricing.we-start-by-aligning-on-goals": "We start by aligning on goals, scope, and success metrics.",
  "pricing.30": "30%",
  "pricing.img-staging": "/amfire-design/pricing/staging.png",
  "pricing.design-backend-on-staging": "Design + backend on staging",
  "pricing.you-pay-when-the-design-is": "You pay when the design is approved and backend is live on staging.",
  "pricing.25": "25%",
  "pricing.img-ai": "/amfire-design/pricing/ai.png",
  "pricing.ai-integration-complete": "AI integration complete",
  "pricing.you-pay-when-ai-features-are": "You pay when AI features are integrated and tested.",
  "pricing.25-2": "25%",
  "pricing.img-launch": "/amfire-design/pricing/launch.png",
  "pricing.production-launch": "Production launch",
  "pricing.you-pay-when-everything-is-live": "You pay when everything is live and ready for real users.",
  "pricing.questions-answered": "Questions, answered",
  "pricing.do-you-offer-payment-plans": "Do you offer payment plans?",
  "pricing.yes-every-tier-is-milestone-based": "Yes — every tier is milestone-based. You pay in stages as work is delivered, never upfront in full.",
  "pricing.what-if-the-project-goes-over": "What if the project goes over budget?",
  "pricing.fixed-price-guarantee-the-quoted-price": "Fixed-price guarantee — the quoted price is the price. Scope changes are quoted before any billing.",
  "pricing.who-owns-the-code": "Who owns the code?",
  "pricing.you-do-100-of-the-ip": "You do. 100% of the IP transfers to you on final payment.",
  "pricing.not-sure-which-tier-fits": "Not sure which tier fits?",
  "pricing.get-a-proposal": "Get a Proposal",
  "products.we-don-t-just-build-for": "We don't just build for clients.",
  "products.we-build-for-the-world": "We build for the world.",
  "products.services-build-custom-solutions-for-your": "Services build custom solutions for your business. Products solve common problems for everyone.",
  "products.view-services": "View Services →",
  "products.live": "Live",
  "products.ai-career-copilot": "AI Career Copilot",
  "products.ai-powered-career-roadmap-generator-for": "AI-powered career roadmap generator for Indian students — chat, roadmaps, and college matching in English or Hindi. Built end-to-end by amfire, live inside Skillship.",
  "products.try-the-beta": "Try the beta →",
  "products.watch-demo": "Watch demo",
  "products.1-400": "1,400+",
  "products.career-paths": "Career paths",
  "products.12": "12+",
  "products.skill-domains": "Skill domains",
  "products.2-5s": "<2.5s",
  "products.response": "Response",
  "products.92": "92%",
  "products.accuracy": "Accuracy",
  "products.hi-what-class-are-you-in": "Hi! What class are you in?",
  "products.class-11-pcm": "Class 11, PCM 🙂",
  "products.interested-in-ai-or-core-engineering": "Interested in AI or core engineering?",
  "products.ai-definitely": "AI, definitely",
  "products.here-s-a-roadmap-b-tech": "Here's a roadmap → B.Tech CSE (AI) · 3 target colleges · 2 skill tracks 🔥",
  "products.amazing-thank-you": "Amazing, thank you!",
  "products.more-products-in-the-works": "More products in the works",
  "products.we-re-turning-the-problems-we": "We're turning the problems we solve for clients into products anyone can use. Want early access?",
  "products.join-the-waitlist": "Join the waitlist",
  "products.talk-white-label-custom": "Talk white-label / custom",
  "services.what-we-do": "What We Do",
  "services.capabilities": "Capabilities,",
  "services.not-verticals": "not verticals",
  "services.full-stack-development-with-an-ai": "Full-stack development with an AI-first approach — delivered with the transparency of a live client portal. Whatever you're building, our process adapts.",
  "services.01": "01",
  "services.amfire-dev-clients": "amfire.dev/clients",
  "services.export": "export",
  "services.default": "default",
  "services.portal": "Portal() {",
  "services.text": "  ",
  "services.const": "const",
  "services.rows": "rows =",
  "services.await": "await",
  "services.getclients": "    getClients()",
  "services.text-2": "  ",
  "services.return": "return",
  "services.text-3": "    <",
  "services.layout": "Layout",
  "services.nav": "nav={",
  "services.nav-2": "nav",
  "services.text-4": "}>",
  "services.text-5": "      <",
  "services.hero": "Hero",
  "services.text-6": "/>",
  "services.text-7": "      <",
  "services.grid": "Grid",
  "services.rows-rows": "rows={rows} />",
  "services.text-8": "    </",
  "services.layout-2": "Layout",
  "services.text-9": ">",
  "services.text-10": "  )",
  "services.text-11": "}",
  "services.amfire": "AMFIRE",
  "services.building-digital-products-that-make-impact": "Building digital products that make impact",
  "services.get-in-touch": "Get in touch",
  "services.web-development": "Web Development",
  "services.platforms-that-run-your-business": "Platforms that run your business.",
  "services.saas-platforms-with-admin-dashboards": "SaaS platforms with admin dashboards",
  "services.client-portals-with-real-time-updates": "Client portals with real-time updates",
  "services.enterprise-web-applications": "Enterprise web applications",
  "services.react": "React",
  "services.next-js": "Next.js",
  "services.typescript": "TypeScript",
  "services.postgresql": "PostgreSQL",
  "services.view-skillship": "View Skillship →",
  "services.02": "02",
  "services.mobile-apps": "Mobile Apps",
  "services.native-cross-platform-offline-ready": "Native & cross-platform, offline-ready.",
  "services.react-native-apps-ios-android": "React Native apps (iOS + Android)",
  "services.progressive-web-apps": "Progressive Web Apps",
  "services.offline-capable-applications": "Offline-capable applications",
  "services.react-native": "React Native",
  "services.expo": "Expo",
  "services.pwa": "PWA",
  "services.view-mygreenhome": "View MyGreenHome →",
  "services.messages": "Messages",
  "services.reports": "Reports",
  "services.this-week": "This week",
  "services.18-240": "18,240",
  "services.dashboard": "Dashboard",
  "services.today": "Today",
  "services.active-users": "Active users",
  "services.24-6k": "24.6K",
  "services.engagement": "Engagement",
  "services.68-4": "68.4%",
  "services.overview": "Overview",
  "services.live": "Live",
  "services.revenue": "Revenue",
  "services.42-8k": "$42.8K",
  "services.03": "03",
  "services.request": "Request",
  "services.review-last-week-s-signups-and": "Review last week's signups and tell me where we're losing people.",
  "services.agent": "Agent",
  "services.reasoning": "Reasoning",
  "services.action-plan": "Action plan",
  "services.pull-funnel-data": "Pull funnel data",
  "services.find-the-drop-off": "Find the drop-off",
  "services.draft-the-fix": "Draft the fix",
  "services.analytics": "Analytics",
  "services.warehouse": "Warehouse",
  "services.crm": "CRM",
  "services.slack": "Slack",
  "services.ai-agents": "AI Agents",
  "services.intelligence-that-works-24-7": "Intelligence that works 24/7.",
  "services.llm-integration-gpt-gemini-claude": "LLM integration (GPT, Gemini, Claude)",
  "services.multi-agent-orchestration-systems": "Multi-agent orchestration systems",
  "services.rag-systems-for-document-intelligence": "RAG systems for document intelligence",
  "services.langchain": "LangChain",
  "services.langgraph": "LangGraph",
  "services.chromadb": "ChromaDB",
  "services.view-ai-career-copilot": "View AI Career Copilot →",
  "services.04": "04",
  "services.automation": "Automation",
  "services.build-once-automate-forever": "Build once, automate forever.",
  "services.whatsapp-business-automation": "WhatsApp Business automation",
  "services.crm-erp-integrations": "CRM & ERP integrations",
  "services.workflow-automation-engines": "Workflow automation engines",
  "services.n8n": "n8n",
  "services.fastapi": "FastAPI",
  "services.rest-graphql": "REST / GraphQL",
  "services.see-how-it-works": "See how it works →",
  "services.trigger": "Trigger",
  "services.new-form-submission": "New form submission",
  "services.process": "Process",
  "services.validate-enrich": "Validate & enrich",
  "services.action": "Action",
  "services.notify-the-owner": "Notify the owner",
  "services.result": "Result",
  "services.crm-updated": "CRM updated",
  "services.runs": "Runs",
  "services.1-245": "1,245",
  "services.success": "Success",
  "services.98-6": "98.6%",
  "services.manual-steps": "Manual steps",
  "services.05": "05",
  "services.code": "Code",
  "services.build": "Build",
  "services.test": "Test",
  "services.deploy": "Deploy",
  "services.monitor": "Monitor",
  "services.eu-central-production": "eu-central · production",
  "services.api": "API",
  "services.3-replicas": "3 replicas",
  "services.workers": "Workers",
  "services.2-replicas": "2 replicas",
  "services.postgres": "Postgres",
  "services.primary-read": "Primary + read",
  "services.99-99": "99.99%",
  "services.uptime-90-days": "Uptime, 90 days",
  "services.120ms": "120ms",
  "services.p95-response": "p95 response",
  "services.42": "42",
  "services.deploys-this-month": "Deploys this month",
  "services.cloud-devops": "Cloud & DevOps",
  "services.infrastructure-that-scales-with-you": "Infrastructure that scales with you.",
  "services.aws-gcp-hetzner-architecture": "AWS / GCP / Hetzner architecture",
  "services.ci-cd-pipelines": "CI/CD pipelines",
  "services.docker-containerisation-ssl-dns": "Docker containerisation, SSL + DNS",
  "services.aws": "AWS",
  "services.docker": "Docker",
  "services.github-actions": "GitHub Actions",
  "services.read-our-approach": "Read our approach →",
  "services.06": "06",
  "services.ui-ux-design": "UI / UX Design",
  "services.interfaces-users-actually-enjoy": "Interfaces users actually enjoy.",
  "services.user-research-wireframing": "User research & wireframing",
  "services.figma-design-systems": "Figma design systems",
  "services.component-libraries": "Component libraries",
  "services.figma": "Figma",
  "services.tailwind": "Tailwind",
  "services.framer-motion": "Framer Motion",
  "services.see-a-design-system": "See a design system →",
  "services.pages": "Pages",
  "services.web-app": "Web app",
  "services.mobile": "Mobile",
  "services.components": "Components",
  "services.card": "Card",
  "services.button": "Button",
  "services.input": "Input",
  "services.headline": "Headline",
  "services.supporting-line-goes-here": "Supporting line goes here",
  "services.primary-action": "Primary action",
  "services.186-96": "186 × 96",
  "services.color": "Color",
  "services.type": "Type",
  "services.aa": "Aa",
  "services.display": "Display",
  "services.aa-2": "Aa",
  "services.body": "Body",
  "services.spacing": "Spacing",
  "services.industry-agnostic-by-design": "Industry-Agnostic by Design",
  "services.we-specialise-in-capabilities-not-verticals": "We specialise in capabilities, not verticals",
  "services.edtech-iot-hospitality-or-something-brand": "EdTech, IoT, hospitality, or something brand new — the process adapts to your problem, not the other way around.",
  "services.start-a-conversation": "Start a conversation",
  "work.real-work": "Real work.",
  "work.real-impact": "Real impact.",
  "work.from-edtech-platforms-to-iot-automation": "From EdTech platforms to IoT automation — the products we've shipped, and the numbers behind them.",
  "work.20": "20+",
  "work.schools-automated": "Schools automated",
  "work.50": "50+",
  "work.iot-installations": "IoT installations",
  "work.1-400": "1,400+",
  "work.career-paths": "Career paths",
  "work.all": "All",
  "work.web": "Web",
  "work.mobile": "Mobile",
  "work.ai": "AI",
  "work.automation": "Automation",
  "work.edtech": "EdTech",
  "work.skillship-ai-powered-lms": "Skillship — AI-powered LMS",
  "work.8-ai-labs-teacher-certification-adaptive": "8 AI labs · teacher certification · adaptive learning · 20+ schools",
  "work.iot-mobile": "IoT · Mobile",
  "work.mygreenhome": "MyGreenHome",
  "work.smart-home-automation": "Smart-home automation",
  "work.live-product": "Live Product",
  "work.ai-career-copilot": "AI Career Copilot",
  "work.bilingual-career-ai": "Bilingual career AI",
  "work.need-something-built": "Need something built?",
  "work.every-project-starts-with-a-conversation": "Every project starts with a conversation, not a contract.",
  "work.start-a-project": "Start a project",
  "image.rw-laptop-shot": "",
  "image.psh-shot-skillship": "",
  "image.psh-shot-copilot": "",
  "image.psh-shot-greenhome": "",
  "image.cs-hero-shot": "",
  "image.cs-step-1": "",
  "image.cs-step-2": "",
  "image.cs-step-3": "",
  "wizard.step": "Step {n} of {total}",
  "wizard.timeline-title": "How soon do you want to start?",
  "wizard.timeline-sub": "A rough answer is fine \u2014 it shapes how we staff the build.",
  "wizard.timeline-1": "ASAP",
  "wizard.timeline-2": "1\u20133 months",
  "wizard.timeline-3": "Just exploring",
  "wizard.details-title": "Tell us about the project",
  "wizard.details-sub": "What are you building, and what does success look like?",
  "wizard.details-placeholder": "A short description of the product, the users, and where you are today\u2026",
  "wizard.contact-title": "Where should we send the proposal?",
  "wizard.contact-sub": "We reply within 24 hours on business days.",
  "wizard.name": "Full name",
  "wizard.email": "Work email",
  "wizard.phone": "Phone (optional)",
  "wizard.company": "Company (optional)",
  "wizard.send": "Send",
  "wizard.sending": "Sending\u2026",
  "wizard.sent-title": "Thanks \u2014 your request is in.",
  "wizard.sent-text": "We review every message within 24 hours and come back with a detailed proposal.",
  "wizard.err-message": "Please add a few more details about the project (at least 10 characters).",
  "wizard.err-contact": "Please enter your name and a valid email address.",
  "wizard.err-send": "Something went wrong. Please try again, or email contact@amfire.in.",
  "newsletter.sending": "\u2026",
  "newsletter.done": "Subscribed \u2014 thanks!",
  "newsletter.error": "That didn't work. Please check the address.",
  "nav.client-login": "Login",
  "footer.client-login": "Login",
};
